Add Singularity.ubuntu-*.04-mlnx-ofed-5.8-2.0.3.0-mvapich-2.3.7
Note, however, mvapich v2.3.7 fails to build for Ubuntu 22.04 LTS [1].
It is unknown whether or not this issue has been address in more recent
versions of mvapich. The problem is the sysctl interface has been
removed in more recent Linux kernels [2].

[1]

make[4]: Entering directory '/tmp/mvapich2-2.3.7/src/pm/hydra/tools/topo/hwloc/hwloc/src'
  CC       topology.lo
topology.c:44:10: fatal error: sys/sysctl.h: No such file or directory
   44 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:870: topology.lo] Error 1

[2]

https://abi-laboratory.pro/index.php?view=changelog&l=glibc&v=2.32